import DOMPurify from "isomorphic-dompurify";

const EPHEMERAL_HTML_CONFIG = {
  ALLOWED_TAGS: [
    // Text
    "p",
    "br",
    "strong",
    "em",
    "b",
    "i",
    "ul",
    "ol",
    "li",
    "span",
    "h3",
    "h4",
    "code",
    "pre",
    // Structural
    "div",
    "figure",
    "figcaption",
    "blockquote",
    "hr",
    "table",
    "thead",
    "tbody",
    "tr",
    "th",
    "td",
    // SVG primitives for arrows, diagrams, illustrations
    "svg",
    "path",
    "circle",
    "ellipse",
    "rect",
    "line",
    "polyline",
    "polygon",
    "g",
    "text",
    "tspan",
    "defs",
    "marker",
    "use",
  ],
  ALLOWED_ATTR: [
    // SVG attributes
    "viewBox",
    "xmlns",
    "fill",
    "stroke",
    "stroke-width",
    "stroke-linecap",
    "stroke-linejoin",
    "stroke-dasharray",
    "d",
    "cx",
    "cy",
    "r",
    "rx",
    "ry",
    "x",
    "y",
    "x1",
    "y1",
    "x2",
    "y2",
    "width",
    "height",
    "transform",
    "text-anchor",
    "dominant-baseline",
    "font-size",
    "font-weight",
    "opacity",
    "points",
    "marker-end",
    "marker-start",
    "id",
    "href",
    "refX",
    "refY",
    "markerWidth",
    "markerHeight",
    "orient",
    "markerUnits",
    // Layout/styling via inline style (constrained by FORBID_ATTR below)
    "style",
    // Table
    "colspan",
    "rowspan",
  ],
  ALLOW_DATA_ATTR: false,
  KEEP_CONTENT: true,
};

/** Strip all scripting, handlers, and disallowed tags; safe for dangerouslySetInnerHTML. */
export function sanitizeEphemeralHtml(dirty: string): string {
  return DOMPurify.sanitize(dirty, EPHEMERAL_HTML_CONFIG);
}
